hash-format = "sha256"

[[files]]
file = "config/clienttweaks-common.toml"
hash = "09404b0058e8732cfcb50fc2edafe3ce948c3b2b5a95ce5fbbede10583c35057"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/attribute-tooltip-fix.pw.toml"
hash = "78ea25f1c90f80a44a6828f6add580a54d64d111925d6883c8aa98d049c49996"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "258431b158c3adc8e7bf4ac8ea9cec20def2e3c373294488d72c238bcbd7538a"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "1b31cb793a692d9f692b233eab37e6fed156f7b05c4a2080a75ea6c06c38c178"
metafile = true

[[files]]
file = "mods/better-modlist.pw.toml"
hash = "935b72f643af0d7af244e39cf4a1a29ab7d555a2e31735c206eb4e56d9249317"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "28358fe53c22695b3bf1f93ac2225c46fe3525918b7b993ac36e68a7f0a16fe8"
metafile = true

[[files]]
file = "mods/c2mef.pw.toml"
hash = "92f000167f0c5665fa6f4a351889a58db7235ed8ebdb086a21a28a7024d347ad"
metafile = true

[[files]]
file = "mods/client-tweaks.pw.toml"
hash = "bc820e991af00d765945397d130e2a9e2592148265041cea8754adabf746bd88"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "4063abe583282834b2f78e3b3e6b9ee4d231a680f74c020e405a4ef196f21ee4"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "a4c814876cd9046f9cdbe0a5967edff092adb8c28de2d717ce5fe469d6fbc9a2"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7b32032b0892b53e1e5daf5410b78b4d98b7bdcbe2184f1d643098de36674865"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/forge-config-screens.pw.toml"
hash = "50ec52c5c84ffb604eacdd19b27a5660f6f2e8365b168f108b68a6ccc96fa8ee"
metafile = true

[[files]]
file = "mods/infoplus.pw.toml"
hash = "f06eb9c373ff0ead37f4bf248721aed8b7ebc18206774b02023d639d514f756a"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7ea985404ee4cc9082472c6869ec146309f526e395361b39f2f4c1a43506c41d"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
hash = "d99d1c2d31ef8198c37c853676c71017ed2304d267d0590cbcb6c3658f674d0f"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "457f1d7c34cb8cb605b002fee89d3f0a766eb461ef82236c48cb1196b1e81a97"
metafile = true

[[files]]
file = "mods/max-health-fix.pw.toml"
hash = "878e22c186eea5703c64d0da20a73d2a169986d05da802e2d4ca439c025d0ef3"
metafile = true

[[files]]
file = "mods/mcpitanlibarch.pw.toml"
hash = "b4e09875722b2e89f1911d1d5a123f772bc4127d988cc8b8ee786d88fb68fcd2"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ade41e4315735aa9116a0222b332e03d3f8df6eea301764d40d0bdc40f5e8689"
metafile = true

[[files]]
file = "mods/minecraft-cursor.pw.toml"
hash = "54e37f91dc796c09903d7b32f7620690d56b0f6a06b8174061338825f5f4ba87"
metafile = true

[[files]]
file = "mods/mod-volume-options.pw.toml"
hash = "c87de1276f9e547b6b77f8b3f7df0370fe99c6c81defffea0789ec4a13d6359c"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "ab170eabaeec3e80c59e850a7d8aee32edfffd6a1e40e2c2f44575c69d122054"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "311e6ff7804f35deac9b3bd48bba8708590f1d8b6648048e7a021b4c5583d3fc"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings-forge.pw.toml"
hash = "80c445632e07f9da7c00cdb3beb7f36ffab6b3d46fc16de1e5046f8767328d67"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "c18dd089c44103b56f8edcbd41a071e41a1fcd46094b2c93df5cc5f07853f18b"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/radium.pw.toml"
hash = "ae4d739bbdb025651a884093de72addac0865525b39e603fb575031a59987763"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "5b10404c7917952a2d651f353b99dea51f85df20606b4576d0552ab9dea6ce62"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "b8c7497acbf4890b4609b6b20de7affdd3482fc99af975d9ff6b29c075e1d8a7"
metafile = true

[[files]]
file = "mods/shield-banner-fix.pw.toml"
hash = "bf227a8d1bafde9f421807f4557d7012cd850f1795e3fa5084911a82dc31961e"
metafile = true

[[files]]
file = "mods/smooth-boot-reloaded.pw.toml"
hash = "daf32b14b2274f7aae1cfc76dabd879a4a7f249fa41d039afab48d1d038d6aed"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "0be4976227df8e261fd362889bf8e85b93e224d1b1c3cd2a11b73a9de3b64083"
metafile = true
