hash-format = "sha256"

[[files]]
file = "mods/create.pw.toml"
hash = "fb5c251cf4997fa65ca043bab7c9ecbd02e108031584a3e26276b77d212de23c"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b098789955721d7978854b705ea82efccc99d6e3cd509b4f5972a1d39044e264"
metafile = true
