name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "025f84ed97d4788c461ca94d84572e6d709197ef9b16131e7f34ba621299e542"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
