name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeb8a1990345544fec249f5cdc3e8c4e5357cf00baf0ea0ad23d6d0da30269ef"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
