name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd5556d901941460469062340881b5662e6c2b8e43e1a93df461b97641e37666"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
