name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98b4ffebd0a9092da1a1c9ab3d1f34150de8b69f753e81585b95864f9f63cab7"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
