name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f1b24ff7dd80d4a54dfadbc5f509f69de079dcf0e237f65e91b6982264906da"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
