name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ca5bee30cc97001d5c034f0fdbbadaa42cdb169de4f74cbe802bd58a949a23c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
