name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f93e6401abc02bfc549f7850fb777d1ce2806de180cfc3d1397c1d4645b9ed5d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
