name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e95c8af97899cd9e0a02bdc71f5e38e2a78ed4d4041009249ec223d6eda9df5"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
