name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5facf1dff101edbad9f7747feac56e2919919d93da9995b693814657a0615bee"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
