name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bbf1a2dce5937ed116c36ff706210f763a0dc28f6519548d4bd2ce09c83062d"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
