name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7baf94fce92deec73cefb6e9046f7da7337a9a60fbb5f168cc2f73481dd7aab1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
