name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f326f5b0ddf784efbcf4ebd87c6be674ac8197fa921cf0afa51fda90224044c8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
