name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2085bac6010320defbe4fa9df8b5708cb00ffa85100ea64eb1bab18e6a009282"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
