name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "185495b1ddc47b3c0b5ba1695a6a0b9b4c4b6e1a3384f52652e5479855c26168"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
