name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e670ac592fa2ff06f4e63febcdfac0a0cdea0c29b675f0cdd3eca3e097641ca"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
