name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d8fd4c31bc599383a3acab2973640cb3c6a1a93c9588202fc0fd65c6844fbae"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
