name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8442fad962d0922b7dec93c23199ab553351f08154c158ecfdefe2a7e9a35cf2"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
