name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d886275428dc270b005e13ba3ede2cedfb37d2b54cad89e32b1068798560121"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
