name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e81f4ca7450e61ca23269e159a8ba732b5856760fb14477984b78a57a36d5a72"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
