name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb8b485581ced32b1cc289799285b5ea4231a67f8bc9a7e00deb1605f1a9ec2b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
