name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a25e2a161daa8e9e19ee764d3d2661254122a37d50bdc488bb493a8e45404fcb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
