name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae61a96e0b7f6fe0e3a45ef59a96c27063359edc062994aa48948be56fefc554"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
