name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5097cc2e24b04b4e65a2ee23e99c7cceab02c24216e6e14a4003cb6bb332bd0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
