name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18d9fa57bc192560dc27689b4baa7549a7717d3743cb15749905b6a2075e218d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
