name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd3197eb097ee72bce884e6bf69b21143d0dadccd1bfaaf0b029fc61f66eb0fb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
