#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=back_weapon;render_toggle=false","id=head;render_toggle=false","id=back;render_toggle=false"]

